### ISSUE TITLE
Support for unpack-dependencies

### ISSUE THREAD

**Issue by lfryc** [ianbrandt/m2e-maven-dependency-plugin#1]
Hi Ian,

I ran into the M2E dependency unpacking problem in case Maven tries to extract artifact from workspace.
This issue is described here [1], [2].

Since the issues aren't resolved for years, I don't think it will be resolved in near future. :-)

`unpack-dependencies` M2E connector would allow me to:
- unpack filtered (`**/*.less`) dependencies which contains web-application resources (`META-INF/resources/`)
- generate aggregated resources from those resources using wro4j plugin (for which there is connector already)

Please let me know if I could help you test such addition.

[1] http://jira.codehaus.org/browse/MDEP-187
[2] http://jira.codehaus.org/browse/MDEP-98

**Comment by lfryc** [comment]
Ah, actually I can see m2e connector for maven-dependency-plugin does suffer from same issue as maven plugin itself:

`Error unpacking file: /xyz/richfaces/sandbox/bootstrap/ui/target/classes to: /xyz/richfaces/sandbox/bootstrap/demo/target/generated-resources
org.codehaus.plexus.archiver.ArchiverException: The source must not be a directory. (org.apache.maven.plugins:maven-dependency-plugin:2.4:unpack:test-unpack:generate-resources)`

**Comment by ianbrandt** [comment]
I'd agree that a connector mapping for unpack-dependencies will trip up on MDEP-187 for modules in the same reactor build, but I'll look to implement it anyway for use with external dependencies.  Maybe if nothing else we can funnel more attention to MDEP-187!

**Comment by lfryc** [comment]
Hey Ian,

I have checked implementation, but it really seems it will be hard to work around a issue.

Unless we could modify `MojoExecution` [1] or `BuildContext` [2].

[1] https://github.com/ianbrandt/m2e-maven-dependency-plugin/blob/master/core/src/com/ianbrandt/tools/m2e/mdp/core/MdpBuildParticipant.java#L37
[2] https://github.com/ianbrandt/m2e-maven-dependency-plugin/blob/master/core/src/com/ianbrandt/tools/m2e/mdp/core/MdpBuildParticipant.java#L38

**Comment by michael-o** [comment]
+1 for this!

**Comment by aneesh-joseph** [comment]
m2e resolves the dependency/artifactItem to the outputDirectory of the workspace project if it's open in the workspace and the project which you are building has the resolve from workspace setting turned on.I managed to get around this for the copy and unpack goals by doing the unpack or copy from within the connector itself(without delegating to the plugin).

https://github.com/coderplus/m2e-maven-dependency-plugin/blob/master/core/src/com/coderplus/m2e/dependencycore/CoderPlusBuildParticipant.java

(most of it is copied from the maven-dependency-plugin source)

**Comment by karlvr** [comment]
Registering my interest in this issue! It doesn't seem like you got anywhere with the original plugin author back in 2012? (reading that mail thread). I'm motivated to try to fix this; maybe we need to fork the dependency plugin itself and roll your m2e support into it. Do we have ideas on how to patch the dependency plugin?

@coderplus perhaps you have some thoughts? It looks like you've gone to some decent effort understanding the issue in your fork - but the idea of copying and pasting code feels not as great as forking the original plugin?

**Comment by ianbrandt** [comment]
@karlvr, @coderplus:

Pull request #11 added a lifecycle mapping for unpack-dependencies.  As such I'd like to close this issue, and consolidate discussion of the workspace resolution/MDEP-187 related limitation to issue #2.  Let's pick this up over there if you don't mind.
