### ISSUE TITLE
Support maven-remote-resources-plugin as well

### ISSUE THREAD

**Issue by sewe** [ianbrandt/m2e-maven-dependency-plugin#10]
Said plugin offers very similar functionality to `dependency:unpack`, so maybe that fruit is hanging low enough...

**Comment by aneesh-joseph** [comment]
I have created a separate connector for the maven-remote-resources-plugin @ https://github.com/coderplus/m2e-connector-for-maven-remote-resources-plugin

**Comment by sewe** [comment]
Nice. Thank you very much.

I'll file any issue I find in the new project’s issue tracker.
