### ISSUE TITLE
Installation Fails with Spring STS 3.1.0 & m2e 1.2.0+

### ISSUE THREAD

**Issue by michaeljfazio** [ianbrandt/m2e-maven-dependency-plugin#3]
Can't seem to install on Spring STS 3.1.0 & m2e 1.2.0+.

Not sure if this is easily resolved with a minor version change to MANIFEST.MF required bundles. Would be great to get this going again with out new development environment.

The following error is shown when an install attempt is made:

Cannot complete the install because of a conflicting dependency.
  Software being installed: m2e connector for the Maven Dependency Plugin 0.0.1.201207182213 (com.ianbrandt.m2e.mdp.feature.feature.group 0.0.1.201207182213)
  Software currently installed: m2e - Maven Integration for Eclipse 1.2.0.20120903-1050 (org.eclipse.m2e.feature.feature.group 1.2.0.20120903-1050)
  Only one of the following can be installed at once: 
    Maven Integration for Eclipse JDT 1.0.0.20110607-2117 (org.eclipse.m2e.jdt 1.0.0.20110607-2117)
    Maven Integration for Eclipse JDT 1.0.200.20111228-1245 (org.eclipse.m2e.jdt 1.0.200.20111228-1245)
    Maven Integration for Eclipse JDT 1.2.0.20120903-1050 (org.eclipse.m2e.jdt 1.2.0.20120903-1050)
    Maven Integration for Eclipse JDT 1.1.0.20120530-0009 (org.eclipse.m2e.jdt 1.1.0.20120530-0009)
    Maven Integration for Eclipse JDT 1.0.100.20110804-1717 (org.eclipse.m2e.jdt 1.0.100.20110804-1717)
  Cannot satisfy dependency:
    From: m2e connector for Maven Dependency Plugin 0.0.1.201207182213 (com.ianbrandt.m2e.mdp.core 0.0.1.201207182213)
    To: bundle org.eclipse.m2e.jdt [1.0.0,1.2.0)
  Cannot satisfy dependency:
    From: m2e connector for the Maven Dependency Plugin 0.0.1.201207182213 (com.ianbrandt.m2e.mdp.feature.feature.group 0.0.1.201207182213)
    To: com.ianbrandt.m2e.mdp.core [0.0.1.201207182213]
  Cannot satisfy dependency:
    From: m2e - Maven Integration for Eclipse 1.2.0.20120903-1050 (org.eclipse.m2e.feature.feature.group 1.2.0.20120903-1050)
    To: org.eclipse.m2e.jdt [1.2.0.20120903-1050]

**Comment by ianbrandt** [comment]
Thanks for the issue report.  I believe you are correct that a manifest change should be all that is required (assuming no API changes in 1.2.0).  I'll try to get a new build published as soon as possible.

**Comment by ianbrandt** [comment]
0.0.2.201308011700 released. Works for me on STS 3.3.0 e4.3 with m2e 1.4.0.
