### ISSUE TITLE
Support for m2e 1.3 and up

### ISSUE THREAD

**Issue by afischer211** [ianbrandt/m2e-maven-dependency-plugin#5]
The current version of m2e for Eclipse Juno is 1.3.1. For the next Eclipse-release (Kepler) it will be version 1.4

**Comment by ianbrandt** [comment]
@afischer211:

Thank you for the issue report.  This should be covered by the fix for issue #3, which has been published to the update site.  If you find otherwise please feel free to reopen this issue.

Best regards,

Ian
